# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
    gfxmodeEfi = "1280x1024x32,auto";
    configurationLimit = 5;
  };
  boot.loader.efi.canTouchEfiVariables = false;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  boot.initrd.luks.devices.luksroot = {
    device = "/dev/disk/by-uuid/cd9a4de0-421a-4dfa-b029-ec5d167bee8b";
    allowDiscards = true;
    # fallbackToPassword = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d8273e31-010b-4746-9f3f-74af3895ad7e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/bd487b7d-a609-4548-a6bc-ec1c3fd5490a";
    fsType = "ext2";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/F3A7-9DE7";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/e6abca0d-aa89-423f-a2c1-add077c0d83f";}];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
