# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.netbootxyz.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  boot.initrd.luks.devices.luksroot = {
    device = "/dev/disk/by-uuid/df00d5d2-13d3-4d99-864e-f89169c4b241";
    allowDiscards = true;
    preLVM = true;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/115f53cf-99fc-40eb-8dfc-e448593d09cf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80c5465e-1983-4e22-90e3-d219fb23f6fb";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/199D-2646";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/4d13ef58-33bb-4e0f-95ea-dcfec3371911";
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
